name: ${project.artifactId}
main: ${project.mainclass}
version: ${project.version}
description: ${project.description}
dev-url: ${project.url}
#project lead
author: IhToN
authors: [Gaelitoelquesito, Diemex, bigscary]
#ensure that we are loaded after multiworld plugins
softdepend: [Multiverse-Core, My Worlds, MystCraft, Transporter, WorldGuard, LogBlock]
commands:
    mhc:
        description: Root command for MegaHardCore
        usage: /mhc - Show the main menu
    mhc reload:
        description: Reload the configuration and modules
        usage: /mhc reload
    mhc version:
        description: Shows the version and build number
        usage: /mhc version
    mhc enabled:
        description: Tells you if MegaHardCore is enabled in the world
        usage: /mhc enabled [world]
permissions:
    MegaHardCore.*:
        description: Grant ALL the permission nodes
        default: no
        children:
           MegaHardCore.admin: true
           MegaHardCore.bypass: true
           MegaHardCore.silent.stone_mining_help: true
           MegaHardCore.silent.no_placing_ore_against_stone: true
           MegaHardCore.silent.realistic_building: true
           MegaHardCore.silent.limited_torch_placement: true
           MegaHardCore.silent.no_torches_here: true
    MegaHardCore.admin:
        description: Grants user ability to administrate the plugin.
        default: op
    MegaHardCore.bypass.*:
        description: Grants bypass permission for some extra hard mode rules.
        default: no
        children:
           MegaHardCore.bypass.creepers: true
           MegaHardCore.bypass.bypass: true
           MegaHardCore.bypass.inventory: true
    MegaHardCore.bypass.bypass:
        description: Old permission that will be replaced by subpermissions
        default: no
    MegaHardCore.bypass.creepers:
        description: Player with this permission will bypass all creeper features, but the flaming creepers
        default: no
    MegaHardCore.bypass.inventory:
        description: Player with this permission will not lose additional inventory on death
        default: no
    MegaHardCore.silent.*:
        description: Grants ALL silent permission nodes
        default: no
        children:
           MegaHardCore.silent.stone_mining_help: true
           MegaHardCore.silent.no_placing_ore_against_stone: true
           MegaHardCore.silent.realistic_building: true
           MegaHardCore.silent.limited_torch_placement: true
           MegaHardCore.silent.no_torches_here: true
    MegaHardCore.silent.stone_mining_help:
        description: hides the stone mining help message
        default: no
    MegaHardCore.silent.no_placing_ore_against_stone:
        description: hides the no placing ore against stone message
        default: no
    MegaHardCore.silent.realistic_building:
        description: hides the realistic building message
        default: no
    MegaHardCore.silent.limited_torch_placement:
        description: hides the limited torch placement message
        default: no
    MegaHardCore.silent.no_torches_here:
        description: hides the no torches here message
        default: no